all:
	ptex2pdf -u -l -ot '-synctex=1 -halt-on-error -file-line-error' interim.tex
clean:
	rm -f *.aux *.dvi *.idx *.ilg *.ind *.log *.out *.toc *.fls *.lot *.lol *.lof *.synctex.gz *.fdb_latexmk 
distclean: clean
	rm -f interim.pdf



